version: '3.8'
services:
  mongodb:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: authdb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  mongodb_data:
